# Generated by Django 4.1.1 on 2023-01-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=400)),
                ('designation', models.CharField(max_length=300)),
                ('photo', models.ImageField(upload_to='')),
                ('twitter_link', models.URLField()),
            ],
        ),
    ]
